async page => {
    // Run only against a dedicated Test-Lifecycle.ps1 installation.
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.locator('canvas').first().waitFor({ state: 'visible' });
    await page.keyboard.press('Control+Alt+KeyT');
    await page.waitForTimeout(1500);
    await page.keyboard.type("printf '%s\\n' '", { delay: 30 });
    const cdp = await page.context().newCDPSession(page);
    // keyboard.type uses insertText for non-US characters. A streamed X11
    // desktop needs actual key events, as generated by the Windows keyboard.
    const codes = { 'ç': ['Semicolon', 186], 'ã': ['KeyA', 65], 'á': ['KeyA', 65], 'é': ['KeyE', 69], 'í': ['KeyI', 73], 'ó': ['KeyO', 79], 'õ': ['KeyO', 79], 'ú': ['KeyU', 85], 'ü': ['KeyU', 85], 'ê': ['KeyE', 69] };
    for (const key of 'ação ç áéíóú ãõ ê ü @ / ? |') {
        if (codes[key]) {
            const [code, windowsVirtualKeyCode] = codes[key];
            await cdp.send('Input.dispatchKeyEvent', { type: 'rawKeyDown', key, code, windowsVirtualKeyCode });
            await cdp.send('Input.dispatchKeyEvent', { type: 'keyUp', key, code, windowsVirtualKeyCode });
        } else { await page.keyboard.type(key, { delay: 30 }); }
    }
    await page.keyboard.type("' > /config/t01-typing.txt");
    await page.keyboard.press('Enter');
    await page.keyboard.type("echo $$ > /config/t01-task.pid; ps -p $$ -o lstart= > /config/t01-task.start; while sleep 1; do date +%s > /config/t01-task.tick; done", { delay: 25 });
    await page.keyboard.press('Enter');
    await page.waitForTimeout(2200);
    await page.screenshot({ path: '.local/t01-before-disconnect.png' });
    const url = page.url();
    const replacement = await page.context().newPage();
    await page.close();
    await replacement.waitForTimeout(2200);
    await replacement.goto(url);
    await replacement.setViewportSize({ width: 1920, height: 1080 });
    await replacement.locator('canvas').first().waitFor({ state: 'visible' });
    await replacement.waitForTimeout(2000);
    await replacement.screenshot({ path: '.local/t01-after-reconnect.png' });
    return { url: replacement.url(), title: await replacement.title(), tabClosedAndReopened: true };
}
